### ISSUE TITLE
点击认证后闪退

### ISSUE THREAD

**Issue by lamprose** [RikkaW/YASNAC#11]
机型：小米11
系统：MIUI13.0.6
点击运行SafetyNet认证后  应用闪退
闪退日志：
2022-02-02 03:09:22.140 1138-1213/? E/ANDR-PERF-OPTSHANDLER: Can't process request: noroot_thread is not running
2022-02-02 03:09:22.140 1138-1213/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [7, 3]
2022-02-02 03:09:22.149 6153-6153/? D/BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.safetynet.service.START pkg=com.google.android.gms }
2022-02-02 03:09:22.149 6153-6153/? D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.safetynet.service.START pkg=com.google.android.gms }
2022-02-02 03:09:22.175 1549-4193/? W/ActivityManager: Unable to start service Intent { act=com.google.android.gms.droidguard.service.START pkg=com.google.android.gms } U=0: not found
2022-02-02 03:09:22.175 1549-4193/? W/ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@e2c0933
2022-02-02 03:09:22.176 6153-7544/? W/GmsClient: unable to connect to service: com.google.android.gms.droidguard.service.START on com.google.android.gms
2022-02-02 03:09:22.335 13030-13030/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2022-02-02 03:09:22.335 13030-13030/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: rikka.safetynetchecker, PID: 13030
    java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:220)
        at F5.e(:1)
        at G5.c(:1)
        at j5.o(Unknown Source:8)
        at es.f(:1)
        at ZS.run(Unknown Source:31)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8085)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
2022-02-02 03:09:22.336 13030-13030/? E/MQSEventManagerDelegate: failed to get MQSService.
2022-02-02 03:09:22.336 13030-13030/? D/OOMEventManagerFK: checkEventAndDumpForJE: 0
2022-02-02 03:09:22.336 13030-13030/? E/MQSEventManagerDelegate: failed to get MQSService.
2022-02-02 03:09:22.338 1549-2652/? E/Thanox-Core: onApplicationCrashing: crash rikka.safetynetchecker ProcessRecord{packageName='rikka.safetynetchecker', processName='rikka.safetynetchecker', pid=13030, uid=10026} java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:220)
        at F5.e(:1)
        at G5.c(:1)
        at j5.o(Unknown Source:8)
        at es.f(:1)
        at ZS.run(Unknown Source:31)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8085)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
2022-02-02 03:09:22.340 1549-13177/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2022-02-02 03:09:22.341 1549-3791/? W/ActivityTaskManager:   Force finishing activity rikka.safetynetchecker/.main.MainActivity

**Comment by RikkaW** [comment]
The error occurred inside Play Service SDK. Nothing we can do.

> 2022-02-02 03:09:22.175 1549-4193/? W/ActivityManager: Unable to start service Intent { act=com.google.android.gms.droidguard.service.START pkg=com.google.android.gms } U=0: not found

It should not because no Play Service install since there is check before. I guess that some third-party tools or your system blocks the application to access Play Service, battery optimize features for example.

**Comment by lamprose** [comment]
it works，thank you!
![Uploading IMG_20220202_165049.jpg…]()
