### ISSUE TITLE
⚠️ Crashed while running checker!

### ISSUE THREAD

**Issue by MrCarb0n** [RikkaW/YASNAC#32]
### | System Env
- Magisk: `d7776f65-alpha:MAGISK:R`
- Android R (API 30), SP: April 2022
- GMS: `version 22.18.20 (100300-451484765)`
- Zygisk | MagiskHide enabled/disabled

### | Crashed Log
```FATAL EXCEPTION: main
Process: rikka.safetynetchecker, PID: 17990
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:220)
	at l5.c(:1)
	at l5.a(:1)
	at Q4.n(:2)
	at Vp.a(:3)
	at XO.run(:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by vvb2060** [comment]
Do not use xposed for this app, you are fooling yourself. In a production environment, the validation is on the server and you have no chance to modify it.

**Comment by MrCarb0n** [comment]
Xposed? never had such things in my system. even I mentioned w/o Magisk. Strange!

**Comment by vvb2060** [comment]
```
Process: rikka.safetynetchecker, PID: 17990
java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:220)
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:0)
at com.google.common.io.BaseEncoding$StandardBaseEncoding.trimTrailingPadding(BaseEncoding.java:0)
at com.google.common.io.BaseEncoding.decodeChecked(BaseEncoding.java:0)
at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:0)
at rikka.safetynetchecker.attest.AttestationStatement.getNonce(AttestationStatement.java:0)
at rikka.safetynetchecker.main.MainViewModel.checkSafetyNet$lambda-2(MainViewModel.java:0)
at com.google.android.gms.tasks.zzm.run(zzm.java:0)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
`getNonce()` is null, it's impossible
