### ISSUE TITLE
Add "deprecationInformation" field support

### ISSUE THREAD

**Issue by Displax** [RikkaW/YASNAC#40]
SafetyNet now rolled out new "deprecationInformation" field in their responses (present randomly, not in all responses), which YASNAC can't handle correctly and crashed app.

https://groups.google.com/g/safetynet-api-clients/c/tq4IusNWJus

**Comment by Displax** [comment]
Crash log:
```
FATAL EXCEPTION: main
Process: rikka.safetynetchecker, PID: 12836
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
	at Q4.q(Unknown Source:4)
	at rg.i(Unknown Source:57)
	at Sp.d0(:3)
	at f9.a(Unknown Source:43)
	at X5.a(:2)
	at X5.h0(:8)
	at la.h0(:28)
	at la.g(:2)
	at Ma.k(Unknown Source:35)
	at rg.g(Unknown Source:53)
	at zl.h0(:5)
	at f9.h0(:1)
	at la.h0(:28)
	at la.g(:2)
	at Ma.j(Unknown Source:42)
	at O9.d0(:31)
	at f9.a(Unknown Source:43)
	at X5.a(:2)
	at X5.h0(:8)
	at la.h0(:28)
	at la.g(:2)
	at k3.c(Unknown Source:205)
	at Qp.d0(:25)
	at f9.a(Unknown Source:43)
	at X5.a(:2)
	at X5.h0(:8)
	at la.h0(:28)
	at P9.s(:14)
	at S8.y(:3)
	at la.T(:14)
	at ua.u(:4)
	at Bw.s(:3)
	at iF.t0(:39)
	at R2.doFrame(Unknown Source:8)
	at P2.doFrame(:3)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
